# Generated by Django 6.0.7 on 2026-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_matchqueue_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchqueue',
            name='is_allocated',
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='game_mode',
            field=models.CharField(choices=[('Solo', 'Single (1v1)'), ('Duo', 'Double (2v2)'), ('Trio', 'Triple (3v3)'), ('Squad', 'Quadruple / TPP-4')], default='Squad', max_length=20),
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='room_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='slot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchqueue',
            name='status',
            field=models.CharField(default='Waiting', max_length=20),
        ),
    ]
